/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */

import styles from "../index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

const News: NextPage = () => {
    const [articles, setArticles] = useState([])
    const [loading, setLoading] = useState(true)
    useEffect(() => {
      async function fetchData() {
        setLoading(true)
        const res = await fetch("https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty")
        let data = await res.json()
        data = data.slice(0 , 100)
    
        const articlesArray = await Promise.all(
          data.map(async (id: any) => {
            const articleRes = await fetch(
              `https://hacker-news.firebaseio.com/v0/item/${id}.json?print=pretty`
            );
            // eslint-disable-next-line @typescript-eslint/no-unsafe-return
            return await articleRes.json()
          })
        );
       
        setArticles(articlesArray)
        setLoading(false)
      }
    
      void fetchData()
    }, []);
    

  return (
    <>
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  
    <main className={styles.main}>
    <h1>Hacker News</h1>
    <section className={styles.articles}>
    {loading ? (
        <p>loading...</p>
      ) : (
        articles.map((article:any) => {
          return (
          <section key={article.id}>
            <a href={article.url}><h2 >{article.title}</h2></a>
            <div  className={styles.subheading}>
              <p >By: {article.by}</p>
              <p >score: {article.score}</p>
            </div>
            
            
          </section>
          
          );
        })
      )}
    </section>
  
    </main>
  </>
  
  );
};

export default News;
